
version: '3'

services:

  mongo1:
    container_name: mongo1
    image: mongo:4.4
    command: mongod --dbpath /data/db --port 27017
    ports:
      - 20001:27017
    networks:
      - mongo
    volumes:
      - mongo1:/data/db

volumes:
  mongo1: {}

networks:
  mongo:
    driver: bridge