
version: '3'

services:

  mongo1rs:
    container_name: mongo1rs
    image: mongo:4.4
    command: mongod --dbpath /data/db --port 27017 --replSet mongo1rs
    ports:
      - 20002:27017
    networks:
      - mongo
    volumes:
      - mongo1rs:/data/db

volumes:
  mongo1rs: {}

networks:
  mongo:
    driver: bridge
    name: mongo