
version: '3'

services:

  mongors4:
    container_name: mongors4
    image: mongo:4.4
    command: mongod  --replSet mongors --port 27017 --dbpath /data/db
    ports:
      - 30004:27017
    networks:
      - mongo
    volumes:
      - mongors4:/data/db

volumes:
  mongors4: {}

networks:
  mongo:
    driver: bridge
    name: mongo
